#.----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.
#  | .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#    | |     ____     | || | ____    ____ | || |  _________   | || |    ______    | || |      __      | || |     ______   | || |     ____     | || |  _______     | || |  _________   | |
#    | |   .'    `.   | || ||_   \  /   _|| || | |_   ___  |  | || |  .' ___  |   | || |     /  \     | || |   .' ___  |  | || |   .'    `.   | || | |_   __ \    | || | |_   ___  |  | |
#    | |  /  .--.  \  | || |  |   \/   |  | || |   | |_  \_|  | || | / .'   \_|   | || |    / /\ \    | || |  / .'   \_|  | || |  /  .--.  \  | || |   | |__) |   | || |   | |_  \_|  | |
#    | |  | |    | |  | || |  | |\  /| |  | || |   |  _|  _   | || | | |    ____  | || |   / ____ \   | || |  | |         | || |  | |    | |  | || |   |  __ /    | || |   |  _|  _   | |
#    | |  \  `--'  /  | || | _| |_\/_| |_ | || |  _| |___/ |  | || | \ `.___]  _| | || | _/ /    \ \_ | || |  \ `.___.'\  | || |  \  `--'  /  | || |  _| |  \ \_  | || |  _| |___/ |  | |
#    | |   `.____.'   | || ||_____||_____|| || | |_________|  | || |  `._____.'   | || ||____|  |____|| || |   `._____.'  | || |   `.____.'   | || | |____| |___| | || | |_________|  | |
#    | |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | || |              | |
#    | '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
#    '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'


config-version: 2 # Do not change this

spawn:
  spawn-on-join: false
  spawn-on-death: false